# Generated by Django 2.2.16 on 2022-04-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20220416_1546'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='title_author',
        ),
    ]
